version: '3.4'
services:
  db:
    image: postgres:11.6
    environment:
      POSTGRES_PASSWORD: 'postgres'
    expose:
      - "5432"
    volumes:
      - "channels_db_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    expose:
      - "6379"
    ports:
      - "6379:6379"

volumes:
  channels_db_data:
